embed <drac2>
url = "";
col = "";
c = character();
force = None;
virtue = "https://static.wikia.nocookie.net/darkestdungeon_gamepedia/images/c/c3/Bounty_hunter_heroic.png/revision/latest?cb=20200620202402";
affliction = "https://static.wikia.nocookie.net/darkestdungeon_gamepedia/images/0/0f/Bounty_hunter_afflicted.png/revision/latest?cb=20200620202005";
aff = ['Hopeless', 'Irrational', 'Selfish', 'Abusive', 'Masochistic', 'Paranoid', 'Fearful']
virt = ['Stalwart', 'Courageous', 'Focused', 'Powerful', 'Vigorous']
AbusiveQuotes = ['Foul brigands!', 'Blackguards, all!', 'You tenderfoot fools!', 'Anger me and you roll the dice.', '...', 'I\'m the only professional here, aren\'t I?', 'Amateurs - curse you!', 'Random Action', 'Amateurs, observe!', 'This is no time for greenhorns!', 'Get out of my way!', 'You bickering old hens. Shut the hell up.', 'Quiet yourself. Or I\'ll do it for you.', 'You simpering clotpoles. You\'ll talk us all to death.', '(spits) There\'s what I think of this "alliance."', 'I am weary of your whining!', 'Hmph. A child could do better.', 'You could have killed it, had you any skill.', 'You pathetic twit!', 'Quit fooling about! Or I\'ll kill you myself...', '...', 'Pathetic. (spits)', 'Shove me again and I\'ll put you down.', 'Stay put. Or I\'ll knock you sideways.', 'Sod off.', '(groan)... You bore me.', 'Weaklings! Ten to yourselves!', 'Feh - there\'s no value in the clumsy ministrations of an amateur...', 'No. Your silence is blessing enough.', ];
FearfulQuotes = ['Curse this place!', 'No shame in folding early. I like to keep my winnings.', 'We\'ve been dealt out! Let us go!', '...', 'It\'s a bad hand. That\'s all there is to it.', 'Smells of death here.', '... Bloody gamble from the start.', 'Back up! Bloody hell, BACK UP!', 'Move it!', 'I must...retreat!', 'Not on your bloody life.', 'No! Every hunter knows when they have become the prey!', 'No. Bad Idea.', 'What was that?? You hear that??', 'We\'re dead. Pray to your gods or whate\'er you do.', 'We have no chance. They\'ve sussed us.', 'Ungh.... It is too strong! We should flee!', 'Aw blast... you pitiless bastard!', 'My strike is not so true! I am... failing!', '(desperate growl)', 'Some foul nightmare...', 'We\'ve got no chance... We should run!', 'No... NOOOOOO!', 'RUUUUN!', 'That\'s it! We\'ve been dealt out!', 'We should flee... There\'s nothing for us here!', 'Stay put! Or you\'ll be a deader!', 'Can\'t... move... my legs!', 'I keep telling you there\'s NO TIME!', 'They will SLAUGHTER US! We should go!', '...', ];
IrrationalQuotes = ['My face is the mask, and the mask my face!', 'I shall take out a bounty - on myself! Hehehehe', '...', 'Would\'ve made a damn fine baker. Tsk.', 'Bring me a small dog. So crunchy. Mmm.', 'It\'ll split a hair, smith... or it\'ll split your head.', 'That ale falls to half and I\'ll cut you likewise.', 'Cut me in, brother. I\'ve a mind to murder.', 'Switching Position', 'I\'m retreating - or not?!', 'I\'m folding a flush!', '...', 'Not moving \'til I get that roast pheasant I\'m owed.', 'I must sharpen my axe, plan my attack!', 'Only if you triple my pay. Nay -- quadruple.', 'Random Action', 'Pitter-patter, pitter-patter...', '...', 'Where\'d the bastard go!? Here kitty-kitty-kitty...', 'Been an age since I saw the sun...', 'I feel like fighting... You -- draw your blade!', 'I like your smell. Like burnt dog. (big sniff)', 'Marking Self', '(snarling like a dog)', 'I WILL EAT YOUR CORPSE!', '...', 'HRRRAAAAA!', 'Damaging Self', '(insane grunting and panting)', '...', 'MY BLOOD AND MY HATE!', 'grrrrRRRRRRRAAAAAA!', '...', 'Ace of spades. Your call.', 'Enemy Missed Self', '(snarling like a rabid weasel)', '...', 'YES! SLAUGHTER THEM!', 'Steal my kill and I\'ll gut you.', 'IDIOT! IDIIIIIOOOOOOOT!', 'Better sleep with one eye open, you charlatan...', 'Death! Death! DEAAAAATH!', 'No. ... I SAID NO, WOMAN!', '(cuts self)', '(drools)', '(seething) I hate you! AAAAAAH!', '(draws finger across throat and glares at you)', '(snort)', 'I said I wanted a pony!', 'Touch me and draw back a stump.', 'RAAAAAAH!', 'NAY! I AM INVINCIBLE!', 'Touch me and die.', '(growl)', 'Back! Back, you demon!', 'Leave me! Can\'t you see I\'ve got him right where I want him?', '(insensible wailing)', 'Why - I\'ve forgotten what I look like under this death shroud! Let me look...', 'Did I finish that last job? Is it done? I cannot be sure...', 'Come. No. Closer.', 'Pluck the wings, then watch it squirm...', 'Like meat in the stew... meat in the stew... meat, meat...', ];
MasochisticQuotes = ['Hmph. Blood\'s merely an expense in my line of work.', 'Pain? (snort)', 'Let them come.', '...', 'You wound me, and I\'ll be impressed.', 'Not a weapon\'s been made hasn\'t cut me.', 'Bloody me? Aye... if you can.', 'Switching Position to the Front', 'Try that on me. Go on... try it.', 'Cut me! Come on, ye blaggard, CUT ME!', 'RAAAH!', 'Random Action', '(shrug) Odd scar won\'t hurt my profits.', 'Let\'s make this interesting...', 'I expect your best, fool.', 'One cut for every enemy I\'ve killed... eeehh.... There.', 'Drink enough and the pain turns to pleasure.', 'Just a simple game of knives... what\'s the harm? Heh.', 'Marking Self', 'C\'mere! Try your luck!', 'Yoo hoo. Over here. (snarl)', '...', 'Damaging Self', 'Calm down... calm down... there we are...', 'Blood. Blood. Mmmmm...', 'One more... just one more... COME ON, YE BASTARDS!', 'Haven\'t near bled enough.', 'HA! Fine work, friend!', 'Yes, yes, NOW I\'m awake!', 'Enemy Missed Self', 'No, NO! You pitiful thing!', 'Come on, hit me! HIIIIT MEEEE!', '...', '(creepy grunt)', 'No. I die here.', 'This dirt will do... All ye creatures: COME!', 'What\'s wrong with a little pain? (snickers)', 'Feck off. I rather like this.', 'I chose this line of work for a reason!', 'I need your help, I\'ll bloody well ask for it.', 'I\'m no child. I can suffer pain.', 'No... I enjoy the test.', 'Foolishness. Only blood begets blood.', 'Nay. Let them ply their bloody trade.', 'No, I like blood.', 'I\'d rather see you fight through it.', 'Think I need to teach you a lesson about suffering.', 'Nah. Rather like a little misery.', 'It\'s nothing serious. Begone.', 'I never eat while on the hunt.', 'No. Ravenous is as ravenous does.', ];
ParanoidQuotes = ['(growl)', 'Cut me in proper. Or else.', 'Don\'t you cheat me... the deal was twenty-five percent.', 'Streak\'s about to run dry. You\'ll see.', 'hmph...you are all sneaks.', 'Look in those eyes... Liars, all.', 'Something\'s not right. Think we been had...', 'Can\'t let that one see me... So familiar...', 'I know that one... Did you follow me?', 'More are coming! I know it!', 'No - they\'ll expect that!', 'No. They\'ll see that coming.', 'And play right into their hands? Foolish.', 'Random Action', 'I prefer to keep them guessing.', 'These ones are sly - I must improvise!', 'They\'re just waiting for us to slip up.', 'You smell that? We\'re being hunted.', 'Some foul whisper on the wind....', 'Eat your share, and no more. I\'m watching...', 'Backstabbing liar!', 'Been waiting for this moment!', '(spits) Knew you\'d try to swindle me!', 'Right into a bigger trap, I bet!', 'Too strong! They know our weaknesses!', '... Someone told them where we\'d be!', 'Enemy Missed Self', 'Bastard is after my coin! STAY BACK!', 'You LET it come at me! TRAITOR!', 'I knew it... You\'re with them!', 'You backstabbing son of a...', 'I told you! They know our weaknesses!', 'Someone fouled up!', 'I knew it... You\'re with them!', 'Huh. How easily they missed you...', 'No. Stay there, so I can see you...', 'You WOULD like that...', 'Refuses to Use Item', '(bats away your hand) Don\'t touch me!', 'Ha! You\'ve always thought I was weak!', 'Refuses to Get Healed', '(snarl)', 'Don\'t you touch me.', 'Back. I know what you want.', 'Refuses to Get Buffed', 'No more of your interference!', '(snort) I fare well enough on my own.', 'You stay away from me...', 'Ha. I think not.', 'Where is my cowl?! WHERRRE IS IT?!', 'Forget it. They are not my allies...', 'Stay away from me.', 'What\'s this? More "majick?" (snort)', 'Keep your sorcery to yourself.', 'I don\'t trust you.', '(spits) Poison!', ];
HopelessQuotes = ['...', 'Life. What a pot of dung.', '... Shoulda written a will.', 'Lucky I\'ve lived this long, I suppose.', 'Been luckier\'n most. But luck always runs out.', 'Snake eyes again...', 'This job\'s impossible.', 'Switching Position to the Front', '...', 'Nothin\' for it, I suppose.', 'This way, that way, it matters not.', 'Not putting my neck on the line for this...', 'I slink back to the shadows...', 'Bah. To hell with it.', 'Bloody hell, why?', 'I didn\'t plan for this...I should have.', '...', 'Random Action', 'What does it matter? We\'ve lost.', 'Bah. Your strategy is a failure.', '(growl) I told you... It is pointless.', '...', '(sigh) Could be plundering villages right now...', 'We\'re all gonna die. Know that, and move on.', 'Marking Self', '...', '(grinds teeth) Stop wasting my time...', 'Damaging Self', 'That\'s enough... More than enough.', 'I\'ve had it with this life...', 'Sleep in the bed what your made, I say.', '(snort) Kill or be killed, I say.',  'Stay back. I\'m not worth it...', 'It\'s useless! Leave me be!', 'No... no, I\'ve had enough.', 'You can\'t help me.', 'Begone. Leave me to my end.', 'Back off.', 'No. Just go away.', 'Don\'t waste it on me.', '...', 'Leave me alone.', 'Why? We\'ve played and lost, plain and simple.', 'Just leave me alone...', 'You waste your time on me...', 'I cannot... I... I am not hungry,', 'Begone. Leave me to my thoughts.', ];
SelfishQuotes = ['Oops - was my take the largest? Shame that.', 'I make my own luck. Especially when no one\'s looking.', 'I take what I wish.', 'One hay-penny short... Someone is going to die.', 'Fun... but I don\'t do this for free.', 'Twenty-five percent... What hogwash.', 'Never done so much for so little...', 'Switching Position to the Front', 'Get out of my way!', 'That one\'s mine.', 'Move your ass! You\'re blocking me!', 'Think you can do better? Be my guest.', 'Not paid enough for this...', 'That\'s enough getting beat on. Your turn.', 'I charge double for that.', '... That wasn\'t in my contract.', 'Best you let me handle this...', 'Random Action', 'Sod off. You don\'t command me.', 'And let you pilfer my take? (snort)... Never.', 'I have this in hand. Go.', 'Hmph... This job\'s practically charity.', 'Think I\'m actually losing money on this expedition...', 'You want me to... share... my pipe-weed? AH-Ha-HAAAAA!', 'GRRR! One more like that and you\'re on your own!', 'Get our of my way! LEMME AT \'EM!', 'Hmph. You owe me one.', 'Get out of my way! You\'re fouling up my aim!', 'Stupid child! You don\'t deserve your twenty-five percent!', 'They should give me your share...', '... I look like a "nice" person to you?', 'I\'m busy... counting my coin.', 'What I need is a nap, and what I need comes first.', ];
VigorousQuotes = ['Feel good. Feel like killing.', 'Slaying time.', 'Self Healing', 'Nothing will stop me.', 'Bloody cakewalk.', ];
StalwartQuotes = ['Been through worse.', 'Easier than I thought.', '(snort) Laughable, mate.', 'I come prepared. Always.', ];
PowerfulQuotes = ['RRRRAAAAAA!', 'MMMRRRRAAAAAAA!', 'RAAAAAAAH!', 'Win this, and the tavern\'s on me.', ];
CourageousQuotes = ['Tis tough... Not tough enough.', 'I go first.', 'Keep yourselves together. T\'aint so bad.', 'Take heart, I have a plan!', ];
FocusedQuotes = ['I live for this.', 'Everything bleeds. You watch.', '(slaps ally) Focus up, damn you - now is the time to hunt!', 'Get angry, get even!', ];
base = f''' -title "{name}'s resolve is tested!" ''';
dc = 18; wisMod = wisdomSave;
args = argparse(&ARGS&);
force = 1 if args.last("virtue") else -1 if args.last("affliction") else 0;
style = "***";
save = vroll ("1d20+" + wisMod)
base += f''' -f "Meta|**DC: {dc}**" ''';
base += f''' -f "Affliction Check|{save.result}" ''' if save else "";
stress = c.get_cc("Stress");
if force == -1 or (save.total < dc and force == 0):
	url = affliction;
	res = randchoice(aff);
	c.set_cc("Stress", 12);
	q = get(res + "Quotes");
	base += f''' -f "{name} is {res}!|{style}{randchoice(q)}{style}" ''';
	col = "#ff0000";
else:
	url = virtue;
	res = randchoice(virt);
	c.set_cc("Stress", 2);
	q = get(res + "Quotes")
	base += f''' -f "{name} is {res}!|{style}{randchoice(q)}{style}" ''';
	col = "#f1eede";
base += f''' -thumb "{url}" ''';
nStress = c.get_cc("Stress");
_str = "";
if nStress != stress:
	_str = f' ({"+" if nStress > stress else ""}{nStress-stress})';
base += f''' -footer "Stress: {character().cc_str('Stress')}{_str}" -color "{col}" '''
return base;
</drac2>